interface EnvironmentVariables {
  DATABASE_URL: string;
  PORT: number;
  ACCESS_TOKEN_SECRET: string;
  FRONTEND_ORIGIN: string;
  GITHUB_OAUTH_CLIENT_ID: string;
  GITHUB_OAUTH_CLIENT_SECRET: string;
  GITHUB_OAUTH_CALLBACK_URL: string;
  GOOGLE_OAUTH_CLIENT_ID: string;
  GOOGLE_OAUTH_CLIENT_SECRET: string;
  GOOGLE_OAUTH_CALLBACK_URL: string;
}
