# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Create and publish a Docker image for the backend

on:
  push:
    branches:
      - dev
    paths:
      - backend/**

jobs:
  build-and-push-backend-image:
    uses: ./.github/workflows/ghcr-image-release.yml
    permissions:
      contents: read
      packages: write
    with:
      tag: "dev"
      build-namespace: "backend"
      repository-name: ${{ github.repository }}
      github-actor: ${{ github.actor }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
